name: Pull Request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run test:unit
      - run: npm run test:integration
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}